/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Gustavo Davila
 */
public class ViewDiagnostico extends javax.swing.JFrame {

    /**
     * Creates new form ViewDiagnostico
     */
    public ViewDiagnostico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imagen_medico = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cb_sintoma1 = new javax.swing.JComboBox<>();
        cb_sintoma2 = new javax.swing.JComboBox<>();
        cb_sintoma3 = new javax.swing.JComboBox<>();
        btn_diagnosticar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        A_descripcion = new javax.swing.JTextArea();
        JlabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imagen_medico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/user_medico.jpeg"))); // NOI18N
        jPanel1.add(imagen_medico, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, 210));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("Sintoma 1:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 287, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Sintoma 2:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setText("Sintoma 3:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, 30));

        cb_sintoma1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(cb_sintoma1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 410, -1));

        cb_sintoma2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(cb_sintoma2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 410, -1));

        cb_sintoma3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(cb_sintoma3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 410, -1));

        btn_diagnosticar.setText("Diagnosticar");
        jPanel1.add(btn_diagnosticar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 120, -1));

        A_descripcion.setColumns(20);
        A_descripcion.setRows(5);
        jScrollPane1.setViewportView(A_descripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 410, 80));

        JlabelFondo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JlabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/wallpaper4.jpg"))); // NOI18N
        jPanel1.add(JlabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 665, 656));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDiagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDiagnostico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea A_descripcion;
    private javax.swing.JLabel JlabelFondo;
    public javax.swing.JButton btn_diagnosticar;
    public javax.swing.JComboBox<String> cb_sintoma1;
    public javax.swing.JComboBox<String> cb_sintoma2;
    public javax.swing.JComboBox<String> cb_sintoma3;
    private javax.swing.JLabel imagen_medico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
